I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/credits.rpy", line 22, in script
    image cred = Text(credits_speed, font="fonts/Lismonia_Demo.ttf", text_align=0.5) #use this if you want to use special fonts
  File "game/credits.rpy", line 22, in <module>
    image cred = Text(credits_speed, font="fonts/Lismonia_Demo.ttf", text_align=0.5) #use this if you want to use special fonts
NameError: name 'credits_speed' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/credits.rpy", line 22, in script
    image cred = Text(credits_speed, font="fonts/Lismonia_Demo.ttf", text_align=0.5) #use this if you want to use special fonts
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\ast.py", line 981, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/credits.rpy", line 22, in <module>
    image cred = Text(credits_speed, font="fonts/Lismonia_Demo.ttf", text_align=0.5) #use this if you want to use special fonts
NameError: name 'credits_speed' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
 
Fri Jun 28 22:22:01 2019
