I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/ImagePrep.rpy", line 2, in script
    image Aangry1 = im.factorscale("images/Anne/A_Angry_A1.png", .5)
  File "game/ImagePrep.rpy", line 2, in <module>
    image Aangry1 = im.factorscale("images/Anne/A_Angry_A1.png", .5)
AttributeError: 'module' object has no attribute 'factorscale'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/ImagePrep.rpy", line 2, in script
    image Aangry1 = im.factorscale("images/Anne/A_Angry_A1.png", .5)
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\ast.py", line 1011, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\python.py", line 1983, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/ImagePrep.rpy", line 2, in <module>
    image Aangry1 = im.factorscale("images/Anne/A_Angry_A1.png", .5)
AttributeError: 'module' object has no attribute 'factorscale'

Windows-8-6.2.9200
Ren'Py 7.3.0.271
Disconnected 1.0
Tue Jun 25 23:39:27 2019
